name: "godot-ci-mono export"
on:
  push: {}
  pull_request: {}

env:
  GODOT_VERSION: 4.2.1
  EXPORT_NAME: PirateJam14-game
  PROJECT_PATH: piratejam14

jobs:
  export-windows:
    name: Godot Windows Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:mono-${GODOT_VERSION}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable.mono ~/.local/share/godot/templates/${GODOT_VERSION}.stable.mono
      - name: Export
        run: |
          mkdir -v -p build/windows
          godot --headless --verbose --export-release "Windows Desktop" ./build/windows/$EXPORT_NAME.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${EXPORT_NAME}-windows
          path: build/windows
      - name: Itch.io Publish
        uses: yeslaya/butler-publish-itchio-action@v1.0.3
        env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_UPLOAD_API_KEY }}
          CHANNEL: windows
          ITCH_GAME: $PROJECT_PATH
          ITCH_USER: nikkxi
          PACKAGE: ./build/windows
          VERSION_FILE: version.txt


  export-linux:
    name: Linux Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:mono-${GODOT_VERSION}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable.mono ~/.local/share/godot/templates/${GODOT_VERSION}.stable.mono
      - name: Linux Build
        run: |
          mkdir -v -p build/linux
          godot --headless --verbose --export-release "Linux/X11" ./build/linux/$EXPORT_NAME.x86_64
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${EXPORT_NAME}-linux
          path: build/linux
      - name: Itch.io Publish
        uses: yeslaya/butler-publish-itchio-action@v1.0.3
        env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_UPLOAD_API_KEY }}
          CHANNEL: linux
          ITCH_GAME: $PROJECT_PATH
          ITCH_USER: nikkxi
          PACKAGE: ./build/linux
          VERSION_FILE: version.txt