name: "godot-ci-mono export"
on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}

env:
  GODOT_VERSION: 4.2.1
  EXPORT_NAME: PirateJam14-game

jobs:
  export-windows:
    name: Godot Windows Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:mono-4.2.1
    steps:
      - name: Print variables
        run: env
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup .Net
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: '6'
      - name: Setup Godot Templates
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable.mono ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable.mono
      - name: Export
        run: |
          mkdir -v -p build/windows
          godot --headless --verbose --export-release "Windows Desktop" ./build/windows/${EXPORT_NAME}.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${EXPORT_NAME}-windows
          path: build/windows
      - name: Itch.io Publish
        uses: yeslayla/butler-publish-itchio-action@v1.0.3
        env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_UPLOAD_API_KEY }}
          CHANNEL: windows
          ITCH_GAME: piratejam14
          ITCH_USER: nikkxi
          PACKAGE: ./build/windows
          VERSION_FILE: version.txt


  export-linux:
    name: Godot Linux Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:mono-4.2.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup .Net
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: '6'
      - name: Setup Godot Templates
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable.mono ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable.mono
      - name: Linux Build
        run: |
          mkdir -v -p build/linux
          godot --headless --verbose --export-release "Linux/X11" ./build/linux/${EXPORT_NAME}.x86_64
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${EXPORT_NAME}-linux
          path: build/linux
      - name: Itch.io Publish
        uses: yeslayla/butler-publish-itchio-action@v1.0.3
        env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_UPLOAD_API_KEY }}
          CHANNEL: linux
          ITCH_GAME: piratejam14
          ITCH_USER: nikkxi
          PACKAGE: ./build/linux
          VERSION_FILE: version.txt